version: '3.8'

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data

  server:
    container_name: server_temp
    image: cosmtrek/air:latest
    working_dir: /go/src/rest1
    command: air -c ./air.toml
    ports:
      - "8080:3000"
    volumes:
      - ./:/go/src/rest1


volumes:
  postgres-db:


